"use client";

import React, { useState } from "react";
import { Terminal, TrendingUp, DollarSign, Play, RefreshCw, ArrowUpRight, CheckCircle2, Layers, Download, FileText, Share2, Sparkles, Cpu, Check } from "lucide-react";
import { motion, AnimatePresence } from "framer-motion";

const PRESETS = [
  {
    title: "AI Biomarkers for Diagnostic Telemetry",
    pitch: "Edge-AI diagnostic platform analyzing ultrasound metrics on mobile devices to detect early clinical biomarkers in underserved medical infrastructure.",
    burn: 14000,
    cac: 32,
    ltv: 840,
  },
  {
    title: "CleanTech Micro-Grid Decentralized Payments",
    pitch: "Decentralized IoT micro-grid controllers coupled with smart contract payment channels for equipment leasing and energy distribution across emerging markets.",
    burn: 18500,
    cac: 45,
    ltv: 1200,
  },
  {
    title: "Adaptive Quantitative AI Tutoring Infrastructure",
    pitch: "Sovereign AI quantitative mathematics and coding mentor engineered with real-time code verification sandboxes for competitive technical training.",
    burn: 11000,
    cac: 18,
    ltv: 450,
  },
];

export default function FintechEngine() {
  const [pitchText, setPitchText] = useState(PRESETS[0].pitch);
  const [isGenerating, setIsGenerating] = useState(false);
  const [logs, setLogs] = useState<string[]>([
    "[SYSTEM-INIT] Cluster us-east-quant-01 connected and ready.",
    "[QUANT-NODE] Preset parameters loaded. Ready for multi-agent simulation.",
  ]);
  const [modelReady, setModelReady] = useState(true);
  const [copied, setCopied] = useState(false);

  const [monthlyBurn, setMonthlyBurn] = useState(PRESETS[0].burn);
  const [cac, setCac] = useState(PRESETS[0].cac);
  const [ltv, setLtv] = useState(PRESETS[0].ltv);
  const [initialCapital, setInitialCapital] = useState(250000);

  const handleRunSimulation = () => {
    if (!pitchText.trim()) return;
    setIsGenerating(true);
    setModelReady(false);
    setLogs([
      "[IAAS-NODE-04] Allocating secure containerized execution pods...",
      "[QUANT-AGENT-1] Parsing input vectors & sizing TAM/SOM capital pools...",
    ]);

    setTimeout(() => {
      setLogs((prev) => [
        ...prev,
        "[QUANT-AGENT-2] Executing 10,000 Monte Carlo DCF simulations...",
        `[QUANT-AGENT-2] Unit economics verified: CAC to LTV ratio ${(ltv / cac).toFixed(1)}x`,
      ]);
    }, 800);

    setTimeout(() => {
      setLogs((prev) => [
        ...prev,
        "[QUANT-AGENT-3] Indexing vector database of 520+ institutional capital providers...",
        "[STATUS: COMPLETE] 3-Year Institutional DCF Model & Valuation Report generated successfully.",
      ]);
      setIsGenerating(false);
      setModelReady(true);
    }, 1600);
  };

  const handleSelectPreset = (idx: number) => {
    const p = PRESETS[idx];
    setPitchText(p.pitch);
    setMonthlyBurn(p.burn);
    setCac(p.cac);
    setLtv(p.ltv);
  };

  const runwayMonths = (initialCapital / monthlyBurn).toFixed(1);
  const ltvCacRatio = (ltv / cac).toFixed(1);
  const estimatedYear3Revenue = ((initialCapital / cac) * ltv * 0.45).toLocaleString("en-US", {
    style: "currency",
    currency: "USD",
    maximumFractionDigits: 0,
  });

  // Executive Dossier Generation & Download Engine (.json & .md)
  const handleDownloadDossier = (format: "json" | "md") => {
    const dossierData = {
      system: "Lumina Cloud OS - Track 3: ElevateHer",
      timestamp: new Date().toISOString(),
      executionNode: "us-east-quant-01",
      verificationSla: "SOC2 / ZKP Compliant",
      projectSpecification: {
        architectureVector: pitchText,
        initialSeedCapital: initialCapital,
        monthlyBurnRate: monthlyBurn,
        runwayMonths: Number(runwayMonths),
        unitEconomics: {
          customerAcquisitionCost: cac,
          lifetimeValue: ltv,
          ltvToCacRatio: Number(ltvCacRatio),
        },
        estimatedYear3Revenue: estimatedYear3Revenue,
      },
      institutionalMatches: [
        { name: "Sovereign Capital Pool Alpha", matchScore: "98.7%", allocationTranche: "$500k - $1.5M" },
        { name: "Apex Venture Syndicate", matchScore: "96.4%", allocationTranche: "$750k - $2.0M" },
        { name: "Decentralized Escrow Fund", matchScore: "94.1%", allocationTranche: "$150k - $500k" },
      ],
      architectAttribution: "Abhijeet Kangane (Founder & Lead Infrastructure Architect) & Team",
    };

    if (format === "json") {
      const dataStr = "data:text/json;charset=utf-8," + encodeURIComponent(JSON.stringify(dossierData, null, 2));
      const downloadAnchor = document.createElement("a");
      downloadAnchor.setAttribute("href", dataStr);
      downloadAnchor.setAttribute("download", `Lumina-Sovereign-Quant-Dossier-${Date.now()}.json`);
      document.body.appendChild(downloadAnchor);
      downloadAnchor.click();
      downloadAnchor.remove();
    } else {
      const mdContent = `# 🏛️ LUMINA SOVEREIGN QUANTITATIVE DOSSIER
**Generated by:** Lumina Cloud OS (v1.4.0-iaas)  
**Execution Node:** \`us-east-quant-01\` | **ZKP SLA:** Verified  
**Timestamp:** \`${dossierData.timestamp}\`

---

## 1. Project Architecture & Vector Summary
> "${pitchText}"

## 2. Verified Unit Economics & Runway Index
- **Initial Seed Capital:** \`$${initialCapital.toLocaleString()}\`
- **Monthly Burn Rate:** \`$${monthlyBurn.toLocaleString()}/mo\`
- **Projected Cash Runway:** **${runwayMonths} Months**
- **Customer Acquisition Cost (CAC):** \`$${cac}\`
- **Lifetime Value (LTV):** \`$${ltv}\`
- **Unit Economics Ratio (LTV:CAC):** **${ltvCacRatio}x**
- **Year 3 Projected ARR:** **${estimatedYear3Revenue}**

## 3. Institutional Capital Tranche Matches
1. **Sovereign Capital Pool Alpha** — *98.7% Match* (\`$500k - $1.5M\`)
2. **Apex Venture Syndicate** — *96.4% Match* (\`$750k - $2.0M\`)
3. **Decentralized Escrow Fund** — *94.1% Match* (\`$150k - $500k\`)

---
*Architected & Engineered by Abhijeet Kangane (Founder & Lead Infrastructure Architect) & Team.*`;

      navigator.clipboard.writeText(mdContent);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  return (
    <div className="relative max-w-7xl mx-auto py-24 px-4 lg:px-8 overflow-hidden font-sans">
      {/* Background Aurora Blobs for Seamless Landing Aesthetics */}
      <div className="absolute top-1/3 right-10 w-[460px] h-[300px] bg-purple-600/12 rounded-full blur-[140px] pointer-events-none animate-aurora-1" />
      <div className="absolute bottom-1/4 left-10 w-[400px] h-[280px] bg-indigo-600/10 rounded-full blur-[130px] pointer-events-none animate-aurora-2" />

      {/* Header Section */}
      <motion.div
        initial={{ opacity: 0, y: 15 }}
        animate={{ opacity: 1, y: 0 }}
        transition={{ duration: 0.5 }}
        className="text-left mb-12 border-b border-white/10 pb-8 relative z-10"
      >
        <div className="inline-flex items-center gap-2 px-3.5 py-1 rounded-full iaas-panel border border-indigo-500/30 text-indigo-400 text-xs font-mono mb-3 shadow-lg">
          <Layers className="w-3.5 h-3.5 animate-pulse" />
          <span>Sovereign Multi-Agent Valuation Console &bull; Quant Pods us-east-01</span>
        </div>
        <h2 className="text-3xl sm:text-5xl font-heading font-extrabold text-white tracking-tight leading-tight">
          Quantitative Capital &amp; DCF Simulation Suite
        </h2>
        <p className="text-gray-300 text-xs sm:text-sm max-w-3xl mt-2 leading-relaxed font-sans">
          Synthesize institutional-grade 3-year discounted cash flow models, evaluate unit economics in real time, and dispatch verified quantitative dossiers directly to institutional capital endpoints.
        </p>
      </motion.div>

      <div className="grid grid-cols-1 lg:grid-cols-12 gap-8 items-start relative z-10">
        {/* Left Console: Input & Logs */}
        <motion.div
          initial={{ opacity: 0, x: -15 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="lg:col-span-6 flex flex-col gap-6"
        >
          <div className="iaas-panel p-6 rounded-2xl border border-white/10 shadow-2xl">
            <div className="flex items-center justify-between mb-4">
              <span className="text-xs font-mono font-bold text-gray-300 uppercase tracking-wider font-heading">
                1. System Input Parameters
              </span>
              <span className="text-[11px] text-indigo-400 font-mono bg-indigo-500/10 px-2.5 py-0.5 rounded-full border border-indigo-500/20">
                Input format: UTF-8 / Voice Vector
              </span>
            </div>

            {/* Presets Grid */}
            <div className="grid grid-cols-1 sm:grid-cols-3 gap-2.5 mb-4 font-sans">
              {PRESETS.map((p, i) => (
                <button
                  key={i}
                  onClick={() => handleSelectPreset(i)}
                  className="text-left p-3.5 rounded-xl bg-white/[0.03] hover:bg-white/[0.08] border border-white/5 hover:border-indigo-500/40 transition-all text-xs font-medium text-gray-300 flex flex-col justify-between h-22 shadow-sm group"
                >
                  <span className="line-clamp-2 font-bold text-white group-hover:text-indigo-200 transition-colors">{p.title}</span>
                  <span className="text-[10px] text-indigo-400 font-mono mt-1 flex items-center gap-1 font-semibold">
                    <span>Load Vector #{i + 1}</span>
                    <ArrowUpRight className="w-2.5 h-2.5 group-hover:translate-x-0.5 group-hover:-translate-y-0.5 transition-transform" />
                  </span>
                </button>
              ))}
            </div>

            <textarea
              rows={5}
              value={pitchText}
              onChange={(e) => setPitchText(e.target.value)}
              placeholder="Enter comprehensive architecture specification, revenue streams, and unit economic parameters..."
              className="w-full bg-[#090a0f] border border-white/10 rounded-xl p-4 text-xs font-mono text-gray-100 focus:outline-none focus:border-indigo-500 transition-colors resize-none leading-relaxed placeholder:text-gray-600 shadow-inner"
            />

            <button
              onClick={handleRunSimulation}
              disabled={isGenerating || !pitchText.trim()}
              className={`mt-4 w-full py-3.5 rounded-xl font-semibold text-xs font-sans flex items-center justify-center gap-2 transition-all shadow-xl group ${
                isGenerating
                  ? "bg-indigo-600/40 cursor-not-allowed text-gray-400"
                  : "bg-gradient-to-r from-indigo-600 to-purple-600 hover:from-indigo-500 hover:to-purple-500 text-white shadow-indigo-600/30 hover:scale-[1.01]"
              }`}
            >
              {isGenerating ? (
                <>
                  <RefreshCw className="w-4 h-4 animate-spin text-indigo-200" />
                  <span>Executing 10,000 Monte Carlo Pods...</span>
                </>
              ) : (
                <>
                  <Sparkles className="w-4 h-4 text-indigo-200 group-hover:rotate-12 transition-transform" />
                  <span className="text-sm font-bold">Run Quantitative Valuation Simulation</span>
                </>
              )}
            </button>
          </div>

          {/* Real-Time Kubernetes/IaaS Terminal Output */}
          <div className="iaas-panel p-5 rounded-2xl font-mono text-xs bg-[#090a0f] border border-white/10 shadow-xl">
            <div className="flex items-center justify-between pb-3 mb-3 border-b border-white/10 text-gray-400">
              <div className="flex items-center gap-2">
                <Terminal className="w-4 h-4 text-indigo-400 animate-pulse" />
                <span className="font-bold text-gray-200 text-xs font-heading">Execution Telemetry Stream</span>
              </div>
              <span className="text-[10px] text-emerald-400 font-mono bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/20 font-bold">
                Node: us-east-quant-01
              </span>
            </div>

            <div className="space-y-2.5 min-h-[140px] max-h-[180px] overflow-y-auto pr-2 text-[11px] leading-relaxed">
              {logs.map((log, i) => (
                <motion.div
                  key={i}
                  initial={{ opacity: 0, x: -5 }}
                  animate={{ opacity: 1, x: 0 }}
                  transition={{ duration: 0.2 }}
                  className="flex items-start gap-2"
                >
                  <span className="text-indigo-400 font-extrabold">&gt;</span>
                  <span className={log.includes("COMPLETE") ? "text-emerald-400 font-bold" : "text-gray-300 font-medium"}>
                    {log}
                  </span>
                </motion.div>
              ))}
            </div>
          </div>
        </motion.div>

        {/* Right Console: Interactive DCF Sliders & Institutional Matcher */}
        <motion.div
          initial={{ opacity: 0, x: 15 }}
          animate={{ opacity: 1, x: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="lg:col-span-6 flex flex-col gap-6"
        >
          <div className="iaas-panel p-6 rounded-2xl border border-white/10 shadow-2xl">
            <div className="flex items-center justify-between mb-5 pb-3 border-b border-white/10">
              <div className="flex items-center gap-2 font-heading">
                <TrendingUp className="w-4 h-4 text-indigo-400" />
                <span className="text-xs font-mono font-bold text-white uppercase tracking-wider">
                  2. Dynamic DCF Parameters &amp; Unit Economics
                </span>
              </div>
              {modelReady && (
                <span className="px-2.5 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono text-[10px] font-bold">
                  Real-Time Engine Active
                </span>
              )}
            </div>

            <div className="grid grid-cols-1 sm:grid-cols-2 gap-5 bg-white/[0.02] p-5 rounded-xl border border-white/5 mb-6">
              <div>
                <div className="flex justify-between text-xs font-mono mb-1.5">
                  <span className="text-gray-400 font-sans">Monthly Burn Rate</span>
                  <span className="text-white font-bold">${monthlyBurn.toLocaleString()}/mo</span>
                </div>
                <input
                  type="range"
                  min="5000"
                  max="50000"
                  step="1000"
                  value={monthlyBurn}
                  onChange={(e) => setMonthlyBurn(Number(e.target.value))}
                  className="w-full cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs font-mono mb-1.5">
                  <span className="text-gray-400 font-sans">Initial Seed Capital</span>
                  <span className="text-white font-bold">${initialCapital.toLocaleString()}</span>
                </div>
                <input
                  type="range"
                  min="50000"
                  max="1000000"
                  step="25000"
                  value={initialCapital}
                  onChange={(e) => setInitialCapital(Number(e.target.value))}
                  className="w-full cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs font-mono mb-1.5">
                  <span className="text-gray-400 font-sans">Customer Acq. Cost (CAC)</span>
                  <span className="text-white font-bold">${cac}</span>
                </div>
                <input
                  type="range"
                  min="10"
                  max="200"
                  step="2"
                  value={cac}
                  onChange={(e) => setCac(Number(e.target.value))}
                  className="w-full cursor-pointer"
                />
              </div>

              <div>
                <div className="flex justify-between text-xs font-mono mb-1.5">
                  <span className="text-gray-400 font-sans">Lifetime Value (LTV)</span>
                  <span className="text-white font-bold">${ltv}</span>
                </div>
                <input
                  type="range"
                  min="200"
                  max="3000"
                  step="50"
                  value={ltv}
                  onChange={(e) => setLtv(Number(e.target.value))}
                  className="w-full cursor-pointer"
                />
              </div>
            </div>

            {/* Calculated KPI Grid */}
            <div className="grid grid-cols-3 gap-3 text-left mb-6 font-mono">
              <div className="p-3.5 rounded-xl bg-[#090a0f] border border-white/10 shadow-inner">
                <span className="text-[10px] text-gray-400 block font-sans uppercase font-semibold">Runway Duration</span>
                <span className="text-base sm:text-lg font-heading font-extrabold text-white mt-1 block">{runwayMonths} Months</span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#090a0f] border border-white/10 shadow-inner">
                <span className="text-[10px] text-gray-400 block font-sans uppercase font-semibold">LTV : CAC Ratio</span>
                <span className="text-base sm:text-lg font-heading font-extrabold text-indigo-400 mt-1 block">{ltvCacRatio}x</span>
              </div>
              <div className="p-3.5 rounded-xl bg-[#090a0f] border border-white/10 shadow-inner">
                <span className="text-[10px] text-gray-400 block font-sans uppercase font-semibold">Year 3 Est. ARR</span>
                <span className="text-base sm:text-lg font-heading font-extrabold text-emerald-400 mt-1 block">{estimatedYear3Revenue}</span>
              </div>
            </div>

            {/* Executive Dossier Export Engine Bar */}
            <div className="bg-gradient-to-r from-indigo-950/40 via-purple-950/30 to-cyan-950/30 p-4 rounded-xl border border-indigo-500/30 mb-6 flex flex-col sm:flex-row items-center justify-between gap-3 font-sans">
              <div>
                <span className="text-xs font-bold text-white block font-heading flex items-center gap-1.5">
                  <Download className="w-3.5 h-3.5 text-cyan-400" />
                  Executive Sovereign Quant Dossier
                </span>
                <span className="text-[11px] text-gray-300 block mt-0.5">
                  Export institutional 3-year DCF model with verified ZKP parameters.
                </span>
              </div>
              <div className="flex gap-2 w-full sm:w-auto justify-end">
                <button
                  onClick={() => handleDownloadDossier("json")}
                  className="px-3.5 py-2 rounded-lg bg-indigo-600 hover:bg-indigo-500 text-white font-semibold text-xs transition-all flex items-center gap-1.5 shadow-md shadow-indigo-600/30"
                >
                  <FileText className="w-3.5 h-3.5" />
                  <span>Download .JSON</span>
                </button>
                <button
                  onClick={() => handleDownloadDossier("md")}
                  className="px-3.5 py-2 rounded-lg bg-white/10 hover:bg-white/20 text-white font-semibold text-xs transition-all flex items-center gap-1.5 border border-white/15"
                >
                  {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Share2 className="w-3.5 h-3.5" />}
                  <span>{copied ? "Copied MD!" : "Copy Markdown"}</span>
                </button>
              </div>
            </div>

            {/* Institutional Endpoints */}
            <h4 className="text-xs font-mono font-bold text-gray-300 uppercase tracking-wider mb-3.5 font-heading">
              3. Connected Institutional Capital Endpoints
            </h4>

            <div className="space-y-3 font-mono text-xs">
              {[
                { name: "Sovereign Capital Pool Alpha", focus: "Pre-Seed B2B Infrastructure", check: "$500k - $1.5M", match: "98.7%" },
                { name: "Apex Venture Syndicate", focus: "Quantitative FinTech & EdTech", check: "$750k - $2.0M", match: "96.4%" },
                { name: "Decentralized Escrow Fund", focus: "Web3 Infrastructure & AI", check: "$150k - $500k", match: "94.1%" },
              ].map((vc, idx) => (
                <div key={idx} className="p-3.5 rounded-xl bg-white/[0.02] hover:bg-white/[0.06] border border-white/5 hover:border-indigo-500/30 flex items-center justify-between transition-all group">
                  <div>
                    <div className="flex items-center gap-2">
                      <span className="font-bold text-white text-xs font-sans group-hover:text-indigo-200 transition-colors">{vc.name}</span>
                      <span className="text-[10px] px-2 py-0.5 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono font-bold">
                        {vc.match} Match
                      </span>
                    </div>
                    <span className="text-[11px] text-gray-400 font-sans block mt-1">{vc.focus} &bull; Check: <strong className="text-white">{vc.check}</strong></span>
                  </div>

                  <button
                    onClick={() => alert(`Quantitative dossier successfully dispatched to ${vc.name} endpoint via ZKP multi-sig channel.`)}
                    className="px-3.5 py-1.5 rounded-lg bg-white/5 hover:bg-indigo-600 text-gray-300 hover:text-white text-[11px] font-sans font-semibold transition-all flex items-center gap-1 border border-white/10 hover:border-indigo-400 shadow-sm"
                  >
                    <span>Dispatch</span>
                    <ArrowUpRight className="w-3.5 h-3.5" />
                  </button>
                </div>
              ))}
            </div>
          </div>
        </motion.div>
      </div>
    </div>
  );
}
